.meshmagick:
    script: &test_script
    - virtualenv .venv
    - source .venv/bin/activate
    - pip install -e .
    - python setup.py test
    - coverage run setup.py test
    - coverage report
    - rm -r .venv

meshmagick:
    stage: test
    script: *test_script


