.meshmagick:
    script: &test_script
    - /home/dice/anaconda2/bin/virtualenv .venv
    - source .venv/bin/activate
    - pip install pytest pytest-cov
    - /home/dice/anaconda2/bin/conda install -y vtk
    - pip install -e .
    - python setup.py test
    - coverage run setup.py test
    - coverage report
    - rm -r .venv

meshmagick:
    stage: test
    script: *test_script


