{% set data = load_setuptools()%}
package:
  name: meshmagick
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - vtk >=5
    - numpy
    - argcomplete

build:
  entry_points:
    - meshmagick = meshmagick_cli:main

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENCE
  summary: {{data.get('description')}}
