{% set data = load_setuptools()%}
package:
  name: meshmagick
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - vtk >=5
    - numpy
    - argcomplete

build:
  entry_points:
    - meshmagick = meshmagick:main

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: Licence_CeCILL_V2.1-en.txt
  summary: {{data.get('description')}}

#// about:
  #// home: 
  #// license: BSD
  #// license_file: LICENSE
